site_name: MakeTile Docs
nav:
  - Home: index.md
  - Asset Manager (deprecated): asset_manager.md
  - Tile Types: tile_types.md
  - FAQ: faq.md
  - Licensing and Copyright: licensing.md
  - Release Notes: release_notes.md
  
theme: readthedocs
